version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "USER:postgress"
      - "POSTGRES_PASSWORD:"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - bundle:/bundle
      - .:/myapp
      - assets:/myapp/tmp/cache/assets
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres-data:
    driver: local
  bundle:
    driver: local
  assets:
    driver: local